name: FGI - Post to Misskey

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  post-misskey:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          pip install -r requirements.txt
          pip install requests pytz

      - name: Generate image for POST
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: python generate.py --output /tmp/FearGreed_Output.png

      - uses: actions/upload-artifact@v4
        with:
          name: post-image
          path: /tmp/FearGreed_Output.png

      - uses: actions/download-artifact@v4
        with:
          name: post-image
          path: post-image

      - name: Post to Misskey
        env:
          MISSKEY_HOST:  ${{ secrets.MISSKEY_HOST }}
          MISSKEY_TOKEN: ${{ secrets.MISSKEY_TOKEN }}
          IMAGE_PATH:    post-image/FearGreed_Output.png
        run: python post_misskey.py
